[project]
name = "fastapiblog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sarad", email = "thapasarad87@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
fastapiblog = "fastapiblog:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
